### ISSUE TITLE
hm-rega not starting up after update

### ISSUE THREAD

**Issue by chrisx51** [ioBroker/ioBroker.hm-rega#112]
Hello all,
unfortunately, after updating hm-rega i get the following erroros:
(Before it was running without a problem.)
`2020-10-04 00:00:28.438 host.raspberry2 instance system.adapter.hm-rega.1 started with pid 10694
2020-10-04 00:00:28.487 host.raspberry2 instance system.adapter.hm-rega.0 started with pid 10699
2020-10-04 00:00:28.829  /opt/iobroker/node_modules/iobroker.hm-rega/hm-rega.js:617
2020-10-04 00:00:28.830          } catch {
2020-10-04 00:00:28.830                  ^
2020-10-04 00:00:28.830  SyntaxError: Unexpected token {
2020-10-04 00:00:28.830      at createScript (vm.js:80:10)
2020-10-04 00:00:28.831      at Object.runInThisContext (vm.js:139:10)
2020-10-04 00:00:28.831      at Module._compile (module.js:617:28)
2020-10-04 00:00:28.831      at Object.Module._extensions..js (module.js:664:10)
2020-10-04 00:00:28.831      at Module.load (module.js:566:32)
2020-10-04 00:00:28.831      at tryModuleLoad (module.js:506:12)
2020-10-04 00:00:28.832      at Function.Module._load (module.js:498:3)
2020-10-04 00:00:28.832      at Function.Module.runMain (module.js:694:10)
2020-10-04 00:00:28.832      at startup (bootstrap_node.js:204:16)
2020-10-04 00:00:28.832      at bootstrap_node.js:625:3
2020-10-04 00:00:28.832  host.raspberry2 instance system.adapter.hm-rega.1 terminated with code 1 (JS_CONTROLLER_STOPPED)
2020-10-04 00:00:28.833 host.raspberry2 Restart adapter system.adapter.hm-rega.1 because enabled
2020-10-04 00:00:28.848  /opt/iobroker/node_modules/iobroker.hm-rega/hm-rega.js:617
2020-10-04 00:00:28.849          } catch {
2020-10-04 00:00:28.849                  ^
2020-10-04 00:00:28.850  SyntaxError: Unexpected token {
2020-10-04 00:00:28.850      at createScript (vm.js:80:10)
2020-10-04 00:00:28.850      at Object.runInThisContext (vm.js:139:10)
2020-10-04 00:00:28.850      at Module._compile (module.js:617:28)
2020-10-04 00:00:28.850      at Object.Module._extensions..js (module.js:664:10)
2020-10-04 00:00:28.850      at Module.load (module.js:566:32)
2020-10-04 00:00:28.851      at tryModuleLoad (module.js:506:12)
2020-10-04 00:00:28.851      at Function.Module._load (module.js:498:3)
2020-10-04 00:00:28.851      at Function.Module.runMain (module.js:694:10)
2020-10-04 00:00:28.851      at startup (bootstrap_node.js:204:16)
2020-10-04 00:00:28.851      at bootstrap_node.js:625:3
2020-10-04 00:00:28.852  host.raspberry2 instance system.adapter.hm-rega.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2020-10-04 00:00:28.852 host.raspberry2 Restart adapter system.adapter.hm-rega.0 because enabled`

Any ideas?
[iobroker.2020-10-04.log](https://github.com/ioBroker/ioBroker.hm-rega/files/5322884/iobroker.2020-10-04.log)

**Comment by foxriver76** [comment]
Which nodejs version? `node -v && nodejs -v`

**Comment by chrisx51** [comment]
node -v && nodejs -v
v8.12.0
v8.12.0

Indeed, i tried to update this one to 12, but updating froze, so somehow I thought 'never change a running system' Is the upgrad currently mandatory?

**Comment by foxriver76** [comment]
Yes, 8 is EOL and it’s the reason for this issue.

**Comment by foxriver76** [comment]
https://forum.iobroker.net/topic/22867/how-to-node-js-für-iobroker-richtig-updaten

**Comment by chrisx51** [comment]
@foxriver76 Thank you for your hint. I hesitated to do this update, because in the past I struggled a lot with nodejs issue.
I am already updating the adapters as preparation for nodejs update.
And this is also why i seem to have this hm-rega issue.

I will now finalize udpating all adapters, and will then try to update nodejs.
Thanks for your hints!
