### ISSUE TITLE
Strange error with hm-rpc.0.info

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.hm-rega#23]
http://forum.iobroker.net/viewtopic.php?f=22&t=5482

Hallo IoBroker Spezialisten

Ich habe seit heute seltsame Abstürze des IoBroker.
Sagt euch dieses log etwas?
Danach ist alles eingefrohren. kein zugriff per web oder SSH mehr möglich.
am raspi 2 leuchtet nur die HDD LED permanent.

danke im voraus

lg.

```
host.iobroker   2017-02-27 19:26:57.025   info   Restart adapter system.adapter.hm-rega.0 because enabled
host.iobroker   2017-02-27 19:26:57.024   error   instance system.adapter.hm-rega.0 terminated with code 0 (OK)
hm-rega.0   2017-02-27 19:26:56.960   info   terminating
hm-rega.0   2017-02-27 19:26:56.929   error   at Manager.ondata (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:322:16)
hm-rega.0   2017-02-27 19:26:56.929   error   at Decoder.add (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/socket.io-parser/index.js:246:12)
hm-rega.0   2017-02-27 19:26:56.929   error   at Decoder.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
hm-rega.0   2017-02-27 19:26:56.929   error   at Decoder. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
hm-rega.0   2017-02-27 19:26:56.929   error   at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:332:8)
hm-rega.0   2017-02-27 19:26:56.929   error   at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
hm-rega.0   2017-02-27 19:26:56.929   error   at Manager. (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
hm-rega.0   2017-02-27 19:26:56.929   error   at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
hm-rega.0   2017-02-27 19:26:56.929   error   at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
hm-rega.0   2017-02-27 19:26:56.929   error   at Socket. (/opt/iobroker/node_modules/iobroker.hm-rega/hm-rega.js:1353:39)
hm-rega.0   2017-02-27 19:26:56.929   error   TypeError: Cannot set property 'hm-rpc.0.info' of null
hm-rega.0   2017-02-27 19:26:56.909   error   uncaught exception: Cannot set property 'hm-rpc.0.info' of null

```

**Comment by Apollon77** [comment]
see https://github.com/ioBroker/ioBroker.hm-rega/commit/8117029ed7c9cc68c29067429fc4a80d7c23d083 ... opinion please?!

**Comment by Apollon77** [comment]
@GermanBluefox Passt?

**Comment by GermanBluefox** [comment]
@Apollon77 I thought, you merged it.

Passt.

**Comment by Apollon77** [comment]
merged yes, tested and verified that it really really makes sense and do not break other things: no :-)
