### ISSUE TITLE
All object states are not being synchronized in IOBroker (e.g., light switches, etc.).

### ISSUE THREAD

**Issue by Naetschie** [ioBroker/ioBroker.hm-rega#470]
**Describe the bug**
I've been experiencing an issue for about two days where status changes received in the Homatic CCU3 are no longer being synchronized to IOBroker. However, it works fine the other way around. When I set a status in IOBroker, it also reaches the Homatic CCU.

The IOBroker instance is running on a Docker container ("buanet/iobroker") with MACVLan providing its own IP. The ports are currently mapped, probably too many at the moment, but I've been experimenting with them.
  ports:
      - "8081:8081/tcp"
      - "8082:8082/tcp"
      - "8181:8181" 
      - "2323:2323"
      - "3000:3000"
      - "1882:1882"
      - "5683:5683"
      - "42010:42010"

Compose-FILE:

<details>
  <summary>Docker-Compose</summary>
  
networks:
  iobroker-create:
    external: true
    name: "iobroker-create"
  iobroker_default:
    external: true
    name: "iobroker_default"

services:
  iobroker:

    container_name: "iobroker"

    entrypoint:
      - "/bin/bash"
      - "-c"
      - "/opt/scripts/iobroker_startup.sh"

    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "DEBIAN_FRONTEND=teletype"
      - "LANG=de_DE.UTF-8"
      - "LANGUAGE=de_DE:de"
      - "LC_ALL=de_DE.UTF-8"
      - "SETGID=1000"
      - "SETUID=1000"
      - "TZ=Europe/Berlin"

    hostname: "iobroker"

    image: "buanet/iobroker"

    ipc: "private"

    labels:
      com.docker.compose.config-hash: "dfb82537e4a69a5627811317b2fb64b17a5f70c0f3a4d3306df4ea8381c864ac"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:977390c0009c7781e5d39d3fc99ab0895383e90bd5218e8d43b01fadedabb3a6"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "iobroker"
      com.docker.compose.project.config_files: "/data/compose/31/docker-compose.yml"
      com.docker.compose.project.working_dir: "/data/compose/31"
      com.docker.compose.replace: "db5a8c44fd9121b94724d090cefb7bc2fffb239352b8e944ac5d6af72ec26a9a"
      com.docker.compose.service: "iobroker"
      com.docker.compose.version: "2.20.2"
      org.opencontainers.image.authors: "André Germann <info@buanet.de>"
      org.opencontainers.image.base.name: "debian:bookworm-slim"
      org.opencontainers.image.created: "2024-04-15T23:44:49+00:00"
      org.opencontainers.image.description: "Official Docker image for ioBroker smarthome software (https://www.iobroker.net)"
      org.opencontainers.image.documentation: "https://github.com/buanet/ioBroker.docker#readme"
      org.opencontainers.image.source: "https://github.com/buanet/ioBroker.docker"
      org.opencontainers.image.title: "Official ioBroker Docker Image"
      org.opencontainers.image.url: "https://github.com/buanet/ioBroker.docker"
      org.opencontainers.image.version: "v9.1.2"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "iobroker-create"

    ports:
      - "8081:8081/tcp"
      - "8082:8082/tcp"
      - "8181:8181" 
      - "2323:2323"
      - "3000:3000"
      - "1882:1882"
      - "5683:5683"
      - "42010:42010"

    restart: "always"

    volumes:
      - "/var/lib/docker/volumes/iobroker_data:/opt/iobroker"

    working_dir: "/opt/iobroker"

version: "3.6"

  
</details>

**Screenshots & Logfiles**
Here's a screenshot from the log. It looks to me like it's connected as well. The setValue calls have all gone through. After that, I switched directly at the switch, but those changes didn't come through in IOBroker.
![grafik](https://github.com/ioBroker/ioBroker.hm-rega/assets/154509592/ff892c9d-fdab-4cb6-a500-94923a2c45be)

IOBROKER hm-rpc.0 Settings:
![grafik](https://github.com/ioBroker/ioBroker.hm-rega/assets/154509592/4dd12992-c1be-4410-bbaf-b80d7740498a)
![grafik](https://github.com/ioBroker/ioBroker.hm-rega/assets/154509592/19795a36-4373-4f48-b575-fc51f9d7e00e)

Device Manager:
![grafik](https://github.com/ioBroker/ioBroker.hm-rega/assets/154509592/31ac8af0-a1aa-4e98-a521-b1ad6c72201f)

Homatic Firewall andIP
![grafik](https://github.com/ioBroker/ioBroker.hm-rega/assets/154509592/ca63fc2a-c67b-47c6-8fcd-0e465e26d85e)

FritzBox:
![grafik](https://github.com/ioBroker/ioBroker.hm-rega/assets/154509592/eff6f0eb-fda3-47fe-89b5-1a4e56189b74)

**Versions:**
 - hm-rpc version: 1.17.0
 - hm-rega version: 4.0.0
 - JS-Controller version: 7.8
 - Node version:  v18.20.2
 - Operating system: Raspian
 - CCU model: CCU3
 - CCU firmware: 3.75.7

Best Regards,
Stefan

**Comment by Apollon77** [comment]
Was ist vor 2 tagen passiert? Mal CCU neugestartet?

**Comment by Naetschie** [comment]
Hallo, ich hätte kein Ereigenis im Kopf, was das ausgelöst haben kann. Ja CCU mehrfach neugestartet, einmal auch für rund 20 min augelassen. Den Docker-Container vom IOBroker auch mehrfach neu gestartet. Ich hatte nun auch noch ein downgrade von der hm-rega Version gemacht. Hatte auch keine Änderung gebracht.
Hatte nun gerade auch noch ein neuen Dockercontainer erstellt mit dem image... - gleiches verhalten. Mir gehen echt die ideen aus. Es scheint für mich schon ein Problem an meinem aktuellen Setup zu sein, aber ich ich weiß nicht woran es liegt. - Vom gefühl her eben als ob die CCU3 nichtmehr "verschickt" das sich etwas verändert.

**Comment by Naetschie** [comment]
Here is a part of the the Log-File from the CCU3. It seams the Callback got refused.. some1 any idea why?
<details>
  <summary>Log-Error</summary>
024-05-06 08:07:38,202 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-2] SYSTEM: Eventlistener Handler utilization: 1/50 used 
2024-05-06 08:09:12,393 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-2] (un)registerCallback on LegacyServiceHandler called from url: http://raspobroker:42010 
2024-05-06 08:09:12,395 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-2] Removed InterfaceId: iobroker:hm-rpc.0:fd30a9797d096eccc5d601d3e5b1fd2f 
2024-05-06 08:09:46,966 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [vert.x-worker-thread-1] (un)registerCallback on LegacyServiceHandler called from url: http://192.168.178.203:42010 
2024-05-06 08:09:46,972 de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler INFO  [iobroker:hm-rpc.0:2e23f4036e0e91224b1a16f4b8094a79_WorkerPool-0] SYSTEM: LegacyBackendNotificationHandler Verticle or Worker started 
2024-05-06 08:09:46,973 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [iobroker:hm-rpc.0:2e23f4036e0e91224b1a16f4b8094a79_WorkerPool-0] init finished 
2024-05-06 08:09:46,973 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer INFO  [vert.x-worker-thread-4] Added InterfaceId: iobroker:hm-rpc.0:2e23f4036e0e91224b1a16f4b8094a79 
2024-05-06 08:09:46,979 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer ERROR [vert.x-worker-thread-4] IO Exception: Could not add interface: iobroker:hm-rpc.0:2e23f4036e0e91224b1a16f4b8094a79 
de.eq3.cbcs.legacy.communication.rpc.RpcIOException: java.net.ConnectException: Connection refused (Connection refused)
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:110) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
	at com.sun.proxy.$Proxy42.listDevices(Unknown Source) ~[?:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.listDevices(LegacyBackendClient.java:139) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.synchronizedBackendDevices(DeviceUtil.java:163) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:112) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:26) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[?:?]
	at java.net.Socket.connect(Unknown Source) ~[?:?]
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:120) ~[HMIPServer.jar:?]
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179) ~[HMIPServer.jar:?]
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144) ~[HMIPServer.jar:?]
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134) ~[HMIPServer.jar:?]
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612) ~[HMIPServer.jar:?]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447) ~[HMIPServer.jar:?]
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884) ~[HMIPServer.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[HMIPServer.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[HMIPServer.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:106) ~[HMIPServer.jar:?]
	... 15 more

</details>

**Comment by Naetschie** [comment]
Ok i fixed it!
Those two things were (probably) the cause or at least linked to the problem.

Cause my docker runs on MACVLAN 127.0.0.1 is the docker host (probably) and not the docker container.. - I needet to change to eth0. with the correct MACVLAN IP
![328016601-4dd12992-c1be-4410-bbaf-b80d7740498a](https://github.com/ioBroker/ioBroker.hm-rega/assets/154509592/fe60c7fe-9b85-4d05-b63f-e56409c8b69f)

It seams the CCU3 struggled with the DNS. Cause it still tried to contact the wrong IP even i changed it like 2 weeks ago.
![328016624-19795a36-4373-4f48-b575-fc51f9d7e00e](https://github.com/ioBroker/ioBroker.hm-rega/assets/154509592/2dff1de6-a7bd-44fc-82c7-25cdd0056811)


So i do not enterly know why it just appeard a few days ago (maybe i did some update or something i cant remember....) but it seams that was the fix! 

Best Regards
