### ISSUE TITLE
gelöst! hm-rega startet nicht mehr

### ISSUE THREAD

**Issue by ich77** [ioBroker/ioBroker.hm-rega#64]
Hallo zusammen,

seit einiger Zeit startet der hm-rega nicht mehr. Ich habe schon auf der Konsole versucht in neu zu installieren, update und upgrade...

Folgende Fehlermeldung bekomme ich:

instance   system.adapter.hm-rega.0 terminated with code 0 (OK)
--
by   controller[0]: at Decoder.add   (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
by   controller[0]: at Decoder.Emitter.emit   (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
by   controller[0]: at Decoder.<anonymous>   (/opt/iobroker/node_modules/component-bind/index.js:21:15)
by   controller[0]: at Manager.ondecoded   (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
by   controller[0]: at Manager.Emitter.emit   (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
by   controller[0]: at Manager.<anonymous>   (/opt/iobroker/node_modules/component-bind/index.js:21:15)
by   controller[0]: at Socket.onpacket   (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
by   controller[0]: at Socket.onack   (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
by   controller[0]: at Socket.adapter.getForeignObject   (/opt/iobroker/node_modules/iobroker.hm-rega/hm-rega.js:138:54)
by   controller[0]: at Object.decrypt   (/opt/iobroker/node_modules/iobroker.hm-rega/lib/crypto.js:29:31)
by   controller[0]: TypeError: Cannot read property 'length' of undefined
at   Decoder.add (/opt/iobroker/node_modules/socket.io-parser/index.js:246:12)
at   Decoder.Emitter.emit   (/opt/iobroker/node_modules/component-emitter/index.js:134:20)
at   Decoder.<anonymous>   (/opt/iobroker/node_modules/component-bind/index.js:21:15)
at   Manager.ondecoded   (/opt/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
at   Manager.Emitter.emit   (/opt/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
at   Manager.<anonymous>   (/opt/iobroker/node_modules/component-bind/index.js:21:15)
at   Socket.onpacket   (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
at   Socket.onack   (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
at   Socket.adapter.getForeignObject   (/opt/iobroker/node_modules/iobroker.hm-rega/hm-rega.js:138:54)
at   Object.decrypt   (/opt/iobroker/node_modules/iobroker.hm-rega/lib/crypto.js:29:31)
TypeError:   Cannot read property 'length' of undefined
uncaught   exception: Cannot read property 'length' of undefined

**Comment by foxriver76** [comment]
Probier mal `iobroker upload hm-Rega` nutzt du Authentifizierung in den Adaptereinstellungen?

**Comment by ich77** [comment]
Vielen Dank, das hat funktioniert.
